### PR TITLE
UDM support added (CommonJS/Browserify included)

### PR DESCRIPTION
**Pull request by jesusprubio**
Implemented following the [UMD recommendations for jQuery plugins](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js). The same as here: https://github.com/FezVrasta/snackbarjs/pull/14.

But we've a problem, here we have two (independent?) libraries which live in the same codebase. Among the options I found in the wild this is the most reasonable for me, but I'm opened to discuss it with the interested ones :). The idea is to keep a separate folder (with its package.json) in the project structure and this subproject should be also published to NPM.

:)

### CODE REVIEW

**Comment by RomainLanz** [comment]
Squash?

**Comment by jesusprubio** [comment]
Another options I found is to forget the "ripples" specific npm package and use this to do the require:
`require('bootstrap-material/scripts/ripples');`

It works because of the way in how browserify looks for the modules. In fact, if we wanted a more beautiful syntax we could move the ripples.js (in the folder "scripts") to the root, or make a copy, or make another file which requires them.
`require('bootstrap-material/ripples');`

I think I prefer the idea of having different modules.

**Comment by rosskevin** [comment]
For this to cleanly work, I think it depends on #650

**Comment by rosskevin** [comment]
In `v4-dev`, source provides ripples as an es6 module, with related umd packages etc.

**Pull request closed without merging**
