### PR TITLE
Expand

### PR DESCRIPTION
**Pull request by Ironholds**
not adding a link or any kind of "and this is the non-standard thing.." is somewhat deceptive.

### CODE REVIEW

**Comment by FezVrasta** [comment]
implemented by myself. Thanks.

**Comment by Ironholds** [comment]
Implemented _incorrectly_ by yourself. If the author keeps all the rights, that includes the right to distribution and set the terms. In that case, How do you have any right to vary the terms or limit access to the content unless someone gives you money?

It's clear at this stage that you do not have an accurate understanding of copyright law. I would very strongly suggest that you find an existing license that contains the conditions you seek, and use that, rather than attempting to write your own.

**Comment by FezVrasta** [comment]
I think you have not clear the meaning of the word "rights".

Now go in the real world and create your own project and assign to it the license you prefer.

Have a nice day.

**Comment by Ironholds** [comment]
Actually, I have a perfectly fine understanding of the word "rights"; it's one of the things I picked up in my law degree. You are not being transparent about the rights you are having your authors license to you - in fact, you are being actively deceptive about it - and you are being profoundly patronising in your responses to my attempts to fix this state of affairs. On that note, I'm going back to my job, in the "real world", helping run a top-5 website. Do let me know if you have the epiphany that being actively duplicitous and unethical in public is likely to do nothing but burn any reserves of good faith your collaborators may hold.

**Comment by wopian** [comment]
> top-5 website

Top-10\* :speak_no_evil: 

---

+1 on merging this. Worded better and clearer than "This software is share source, this means that the author keep every rights on every edit on this source.",

**Comment by camalot** [comment]
While granting Copyright to a single entity (usually a company) in an open source project is common, The way you are trying to do it will not suffice. The contributor must explicitly grant that, either by signing a document, or posting to a public list. 

If you tried to sell the code from this project in the current state, every contributor to the project would have a case to seek damages. Which brings me back to why it is usually a company that is granted copyright. I don't think you want every contributor to be able to sue you for damages. If it is a company, then your personal assets are not "at risk". 

Please note, I am only trying to offer insight, and help you. I am not trying to insult, or anything like that. I am just providing information, which I think is all others are trying to do as well. If you are not open about your intentions you may see many contributors pissed off, or others afraid to even contribute. This is a bootstrap theme with some sugar, if you piss off the contributors, there is nothing preventing them from creating their own bootstrap theme that does the same thing. And I don't mean by forking your code. The theme itself is basically a derived work from google's material design and bootstrap itself.

**Pull request closed without merging**
