### PR TITLE
Material colors implementation

### PR DESCRIPTION
**Pull request by korgan00**
I think it is stable. This could be a good aproximation. Navbar texts still should be fixed.

### CODE REVIEW

**Comment by FezVrasta** [comment]
sorry I'm having some busy days, I'll try to review this asap

**Comment by korgan00** [comment]
Look at the issue, i tought in a better solution i dont know if i have to implement it.t And tell me if u need anything else. I could do something in my free time to help u ^.^

**Comment by FezVrasta** [comment]
I'm trying to fix the navbar mess, then I'll try to reduce the size of the compiled CSS combining things.

**Comment by FezVrasta** [comment]
I've merged this into master along with some navbar fixes.

There is a problem with the ::placeholder color that is always white... may you try to take a look and let me know if you find some solution?

**Comment by korgan00** [comment]
yeah, i think that what i tell u on the issue (functional programming like) is a good possibility. I could try it in the forked
Maybe it is necesary to separate theming compilation into diferent css (one css for whole color [purple.css, indigo.css...]) to improve performances... there are many colors!

Another posibility is to look at less compilation. It is only a speculation, may be if some declarations are in diferent class block compiles better performance. Explaining:

example 1:

```
.element-material-aplicated@material {
     bg-color: @material-color; 
     text-color: @material-text-color;
}
```

compiles into:

```
.element-material-aplicated-red {
     bg-color: red; 
     text-color: white;
}
.element-material-aplicated-green {
     bg-color: green; 
     text-color: white;
}
```

example 2:

```
.element-material-aplicated@material {
     text-color: @material-text-color;
}
.element-material-aplicated@material {
     bg-color: @material-color; 
}
```

compiles into:

```
.element-material-aplicated-red {
     bg-color: red; 
}
.element-material-aplicated-green {
     bg-color: green; 
}
.element-material-aplicated-green, .element-material-aplicated-red {
     text-color: white;
}
```

Ive dont tested it and i cant now, but is an idea. In 2 colors isnt a performance improvement, but in 500 could be.

**Comment by FezVrasta** [comment]
Consider that the css minifier takes care of combining similar things

**Comment by FezVrasta** [comment]
Please continue at #259

**Pull request merged**
