### PR TITLE
Customizable colors

### PR DESCRIPTION
**Pull request by spiotr12**
1. BMD now uses bootstrap theme-colors map
2. Removed brand colors 
3. Set old brand colors as bmd default colors in theme-colors map

Comments
I've tested scss in angular project and I successfully build css file (`npm run build:css`)

### CODE REVIEW

**Comment by FezVrasta** [comment]
Cool! Going to merge this ASAP

**Comment by spiotr12** [comment]
Will there be a new version to download using npm or do I need to wait for bigger update pack? Thanks! 😄

**Comment by FezVrasta** [comment]
I released 4.1.0 but some JS is broken... fixing it now

**Comment by spiotr12** [comment]
Yes, it should work with standard bootstrap colors override. I've setup your default colors, as a base. I've used it in angular 4 project (scss) and I was able to override them with my custom colors and add more custom colors.

**Pull request merged**
