### PR TITLE
Added new full width readme banner

### PR DESCRIPTION
**Pull request by RobertJGabriel**
Feel free to close, if you dont like it or think its pointless :)

### CODE REVIEW

**Comment by FezVrasta** [comment]
Where's the pink? :(

**Comment by rosskevin** [comment]
I'll revert, I didn't feel strongly one way or the other, just happy for the contribution.

**Comment by RobertJGabriel** [comment]
readme2

Better ? @FezVrasta @rosskevin

**Comment by FezVrasta** [comment]
Yes! :)

**Pull request merged**
