### PR TITLE
Awesome mixin to solve all your problems :P :-)

### PR DESCRIPTION
**Pull request by korgan00**
Placeholder input working correctly in navbar. 
This system should be applyed in all components.
I can do it if needed. If u want to me doing that job, tell it to me. 

Bye!

### CODE REVIEW

**Comment by camalot** [comment]
isn't the css for placeholder ::input-placeholder? Also, not all browsers support that pseudo selector, should use ::-moz-placeholder, :-ms-input-placeholder, and ::-webkit-input-placeholder along with the other.

Am I wrong in what you are trying to accomplish with this pseudo element?

**Comment by korgan00** [comment]
fezvrasta told me to use that because he use autoprefixer tool to add vendor specific ( #259 ). i understand that i should use that psudo-selector, but i can change it if necessary.

**Comment by camalot** [comment]
ok, makes sense. I wasnt aware of that.

**Comment by FezVrasta** [comment]
sorry for the delay, xmas weeks are quite busy :\
I'll work on this after holidays.

**Comment by korgan00** [comment]
ok, no problem

**Comment by FezVrasta** [comment]
Merged.

korgan may you please send me an email? You can send one using the form on my website:

http://mywebexpression.com

Thanks!

**Comment by FezVrasta** [comment]
hi @korgan00 I was trying to use the generic-variations mixin but I can't get it. How should I pass the function as parameter? May you provide a simple example?

Thanks.

**Comment by korgan00** [comment]
background, text and variations are examples itself:

```
.variations(@extra, @property, @default) {
  .generic-variations(@extra, @default, {
      @{property}: @material-color;
    });
}

.background-variations(@extra, @default) {  
  .generic-variations(@extra, @default, {
      background-color: @material-color;
      color: @text-color;
    });
}

.text-variations(@extra, @default) {
  .generic-variations(@extra, @default, {
      color: @material-color;
    });
}
```

There is a more complex example in navbar: 

```
.generic-variations(~"", @primary, {
      background-color: @material-color;
      color: @text-color;
      // deeply defined to override welljumbo class without !impotant need
      .navbar-form {
        .form-control-wrapper input.form-control::placeholder {
          color: @text-color;
        }
        input.form-control::placeholder {
          color: @text-color;
        }
      }
    });
```

**Comment by FezVrasta** [comment]
Thanks!!!

**Comment by FezVrasta** [comment]
@korgan00 I was wondering if you could have some free time to edit this mixin so that it automatically mixes classes with the same properties.

I mean,

``` css
.well-red {
   color: white;
}
.well-black {
  color: white;
}
```

becomes:

``` css
.well-red, .well.black {
  color: white;
}
```

I'm even still waiting a reply to my email

**Comment by korgan00** [comment]
Im too busy now. I have exams during next weeks.
I finish it the 12 of february. Then i will try. :)

It is possible that i didnt recieved any email or may be removed accidentally as trash. 
¿Can u resend it?

**Pull request merged**
