### PR TITLE
updated icon fonts

### PR DESCRIPTION
**Pull request by jmillspaysbills**
updating icon fonts w/ 24px baseline grid.

I still need to add the new CSS, however, I'm not exactly sure where this should go. It seems the only place we have the styles for the icon font are on the compiled CSS in the "dist" directory. However, I don't know if that's the best place for it since we have both SASS and LESS here.

### CODE REVIEW

**Comment by GradyD** [comment]
For the CSS edits you will want to update the `_icons.less` and the `_icons-material-design.less` files.

**Comment by jmillspaysbills** [comment]
I just committed the _icons-material-design.scss and _icons-material-design.less files. Take a look. 

I didn't see an need to update the _icon.less or the _icon.scss files as nothing was changed. Only the data in the "content" property of the individual icon selectors.

**Comment by jmillspaysbills** [comment]
Please let me know what else I need to update.

**Comment by GradyD** [comment]
Hey,

I think you forgot to push your code ;-)

**Comment by jmillspaysbills** [comment]
One thing I was hoping we could review are the two tone icons, like battery level, wifi level, and data level. On the standard icons, the lighter areas are 30% opacity. 

Icon fonts can't have portions of the elements different opacities, so to mimic this, I did similar to what icomoon's premium icon font does, and added small lines that fall on a fraction of the pixel, causing a lighter shade of whatever color the icon is set to. 

This isn't perfect, however, so you will end up seeing the lines if the icons are set to a large size, like 100px for example.

There are other ways where we can recreate this by removing the lighter color areas from those particular icons, then stacking over a full icon set to a lighter opacity. 

We can discuss this further, and I'm happy to do whatever the community decides.

**Comment by FezVrasta** [comment]
Yes would be nice fix the opacity problem... The solution proposed by you seems not enough generic and lot of people could have problems. May you explain better the other option?

**Comment by jmillspaysbills** [comment]
so, font awseome has a class of "stack" that you can add to the icons to stack them on top of each other, see their docs:

http://fortawesome.github.io/Font-Awesome/examples/

So as an example we would have a 20% battery icon and a 100% battery icon and stack them:

```
<span class="mdi-stack">
  <i class="mdi-device-battery-20 mdi-stack-1x"></i>
  <i class="mdi-device-battery-full mdi-stack-1x"></i>
</span>
```

```
.mdi-stack {
  position: relative;
  display: inline-block;
  width: 2em;
  height: 2em;
  line-height: 2em;
  vertical-align: middle;
}
.mdi-stack-1x {
  position: absolute;
  left: 0;
  width: 100%;
  text-align: center;
}
```

It's a little more complex, but there's really no way to get it to look right with only one icon, unfortunately.

**Comment by FezVrasta** [comment]
hey okay I like this idea. May you submit it to this PR?

**Comment by jmillspaysbills** [comment]
Awesome. I can have this done later tonight.

**Comment by FezVrasta** [comment]
Okay thanks!!

**Comment by jmillspaysbills** [comment]
@GradyD I added this about an hour ago:

https://github.com/jmillspaysbills/bootstrap-material-design/commit/b00731de98079a710909e6d3ef39518757300ecd

Did I commit to the wrong fork?

**Comment by GradyD** [comment]
Sorry, I missed the less comment! I don't see any issues in the less file. Also adding bug that this PR is associated with, #445.

Since the UI on this would really be "one" image as the final product couldn't the same thing be mimicked using `:before` and `:after`? That would also be a non breaking change (in theory). The only reason I ask is because it looks like font awesome is using their method to generically combine any of their images. This is a more specific use case. 

The less for that would look something like (I believe)

```
 .mdi-battery-20:before{
     content: "img1";
 }
 .mdi-battery-20:after{
     content: "img2";
 }
```

@FezVrasta what are your thoughts? Personally, I could either way. If icons are going to be stacked it would be important to add to the docs the icons that should be stacked so users are aware of why some icons don't look right.

**Comment by FezVrasta** [comment]
@GradyD ah yea I didn't thought about using the other pseudo element.

I think it would be a more clean solution and, yes, not breaking-change. Personally I vote for it.

What do you think @jmillspaysbills ?

**Comment by FezVrasta** [comment]
related issues:
 #141 #227

**Comment by jmillspaysbills** [comment]
Yeah its definitely cleaner and easier for people using it to build stuff.
We can probably keep the stacked though, as that's similar to font awesome
functionality. I usually mimic the different helper classes when I create
icon fonts.

If you don't want to, we can get rid of those other helper classes. Its up
to you guys.

I'll try to take care of all of this tonight.

**Comment by FezVrasta** [comment]
I think having batteries with the double pseudo-element and even allow users to stack icons would be good.

**Comment by jmillspaysbills** [comment]
Hey guys, I'm working on this now, and I wanted to get your input regarding the multiple icon sizes in the Google Material Icons pack from Google.

not every set, but a few, have a smaller and larger size icon, an 18px and a 36px version. 

Do we want to support the other icon sizes or do we want to stick to 24px?

**Comment by FezVrasta** [comment]
I think keeping the 24px is a good compromise.

**Comment by FezVrasta** [comment]
Any news @jmillspaysbills ?

I'm waiting for you to release the 0.3.0

**Comment by jmillspaysbills** [comment]
Hey guys sorry for the delay. My wife's birthday was this weekend and I didn't get to work at all this weekend.

I just committed these new changes. Let me know if you have any issues with them.

**Comment by jmillspaysbills** [comment]
I updated the _icons-material-design.scss and _icons-material-design.less files as well as replaced the new fonts.

The users shouldn't need to add any extra classes to the icons. They should work as before.

**Comment by FezVrasta** [comment]
thanks @jmillspaysbills, did you already implemented the trick to make battery icons look good? (using `:before` and `:after` pseudo-elements?)

Or should I do it by myself? Let me know so I know how to proceed. Thanks!

**Comment by jmillspaysbills** [comment]
Yes, that is done.

Take a look at the demo page with the new CSS and fonts in place.

It looks awesome on my end.

**Comment by FezVrasta** [comment]
I see these icons...

image

Are you sure have you pushed?

**Comment by GradyD** [comment]
Am I blind again? I am not seeing any changes... Did you `git push` all your changes?

**Comment by jmillspaysbills** [comment]
Hey guys, I committed my changes via the github app.

I haven't really contributed to a git project by forking another project,
so its possible I didn't merge correctly.

I'm not sure how else to do it.

Can I send you guys a zip of my modifications?

**Comment by jmillspaysbills** [comment]
I know this is a giant pain in the ass. Here's the commits. I guess I
checked them into my own branch.

https://github.com/jmillspaysbills/bootstrap-material-design

How do I merge and check into the master?

Sorry for all this confusion.

**Comment by jmillspaysbills** [comment]
https://github.com/jmillspaysbills/bootstrap-material-design/commit/bbac8d92d5d19aaff408850cfe8fd99aeda33c7c

**Comment by GradyD** [comment]
Hey @jmillspaysbills would you be ok with doing a join.me meeting with me? I can help you get your code pushed up.

My email is gradyduncan@gmail.com, you are welcome to email me or send me a hangout invite, either works. If you would prefer you can send me the .zip of changes and I can create a PR. ~~Only downside is you won't get credit for this because my name will be on it...~~ Correction, I believe that I can have the commit show up as you.

**Comment by FezVrasta** [comment]
@GradyD you may publish as him :)

**Comment by FezVrasta** [comment]
ops.. umh

image

what happens?

**Comment by jmillspaysbills** [comment]
it looks like the css didn't compile properly. Are we grabbing the css for the demo from the less file? it looks like the css file for the demo doesn't have the correct content declarations.

**Comment by FezVrasta** [comment]
yes, the `grunt` task compiles less into css...

**Pull request merged**
