### PR TITLE
Fix #327 on ripples.js and improve structure

### LINKED ISSUE #327: Problem when using ripples.js alone
Hello there folks!

I'm trying to use the ripple effect alone! I've included the stylesheets and the scripts, and I'm trying to call it like this: 

``` javascript
  $('#my-button').ripples();
```

But I'm getting this error, when I click it:`Uncaught TypeError: Cannot read property 'createDocumentFragment' of null`

What could I probably be missing? How can I use the ripples.js like this?

Thanks in advance :smile: 

_Ps: I tried including the material.js as well, but I got the same error!_

### PR DESCRIPTION
**Pull request by grvcoelho**
I've fixed #327 and I also passed the plugin to a jQuery Boilerplate structure. I only made changes on the structure and not in the functions themselves, so the  code could be a little bit neater, cleaner and intuitive.

Now the plugin can be accessed alone, by doing: 

``` javascript
$(selector).ripples();
```

Note: I've removed the default elements targeted by the plugin, for IMHO I think that should be in the initialization, and not in the plugin itself.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks, we use doublequotes by default, may you use them?

**Comment by grvcoelho** [comment]
Oh, sorry about that! Absolutely!

**Comment by FezVrasta** [comment]
```
scripts/ripples.js
  line 130  col 32  Missing semicolon.
  line 184  col 4   Missing semicolon.
  line 212  col 4   Missing semicolon.
  line 263  col 4   Missing semicolon.
  line 324  col 70  Missing semicolon.
  line 327  col 4   Missing semicolon.
  ⚠  6 warnings
Warning: Task "jshint:all" failed. Use --force to continue.
Aborted due to warnings.
```

Some other problem with validation, we need to have Travis CI to pass to merge it.

**Comment by grvcoelho** [comment]
@FezVrasta, if there was just that errors, it's fixed now :+1:

**Comment by FezVrasta** [comment]
thanks!

**Pull request merged**
