### PR TITLE
258 primary panel border bottom

### PR DESCRIPTION
**Pull request by kylerberry**
fix for https://github.com/FezVrasta/bootstrap-material-design/issues/258

working pen: http://codepen.io/kylerberry/pen/gbrxGG

### CODE REVIEW

**Comment by kylerberry** [comment]
@FezVrasta not sure why this build is failing

**Comment by FezVrasta** [comment]
I don't know, I'm not on my pc atm, will check tomorrow morning

**Comment by kylerberry** [comment]
@FezVrasta did you ever figure out the issue with travis? It was failing on the phantom.js install

**Comment by FezVrasta** [comment]
It was a config problem

**Pull request closed without merging**
