### PR TITLE
Fix ripple color

### PR DESCRIPTION
**Pull request by npvn**
_ Opacity = 0.3 is too bold. Please review to see if 0.02 is a suitable value.

_ Fix an issue when `window.getComputedStyle` return an `rgba` value and mess up the `targetColor`.

P.S. Not sure why the .css files keep showing up after grunt task?

### CODE REVIEW

**Comment by TransitoryBliss** [comment]
0.02 seems a little bit too transparent don't you think? What's your opinion @FezVrasta

**Comment by FezVrasta** [comment]
Yup I think so

**Comment by npvn** [comment]
I see. Could you have a quick test to see which value should we use?

0.3 is definitely too bold: http://screencast.com/t/fXDuLAuYXnuo

**Comment by npvn** [comment]
@FezVrasta Do you want me to go ahead, pick a value and update this PR?

**Comment by FezVrasta** [comment]
Sorry I had no time to check this, I'll try to find the right value tomorrow

**Comment by FezVrasta** [comment]
I've just checked it.... The polymer implementation has exactly the same value of opacity:

image  
_The upper buttons are the polymer ones, the other ones are our buttons_  

Actually both looks different from the specifications of Google:

google

But even there, the opacity of the ripple looks like the one we use.

**Comment by npvn** [comment]
Oh, I checked again and it turned out opacity level was not the problem. The problem was `$.material.init` being executed multiple times on Meteor and many ripples were created at the same time, making the color look too bold.

I think I know a good solution for this. I'll open a new PR.

I refactored this PR so now it contains only the fix for `targetColor` calculation code. Please take a look and merge this in.

Many thanks for your investigation!

**Pull request merged**
