### PR TITLE
Fix navbar-text on smaller screens (< 1199px)

### PR DESCRIPTION
**Pull request by timhovius**
- Fix that the margin for navbar-text on smaller screens is changing to 15px

### CODE REVIEW

**Comment by Ninir** [comment]
You could maybe split this one in 2, in order to have a better readability for the real fix (margin for navbar-text), and then another one for the coding style, what do you think @timhovius?

**Comment by FezVrasta** [comment]
Yes two commits at least to split the stuff

**Comment by jerone** [comment]
Aldo two different PR's are better here, you could use the following url to help reviewing; https://github.com/FezVrasta/bootstrap-material-design/pull/443/files?w=1

**Comment by timhovius** [comment]
I splitted the commits

**Comment by timhovius** [comment]
Updated commit, removed spacing commit.

**Pull request merged**
