### PR TITLE
Fixed label padding - upstream bootstrap v3 will not be fixed.

### PR DESCRIPTION
**Pull request by HeliumSquid**
Use to look like this:
a

Now looks like this:
b

### CODE REVIEW

**Comment by FezVrasta** [comment]
I think you should tweak the line height instead of playing with paddings

**Comment by HeliumSquid** [comment]
I believe it might be a problem in [bootstrap.css](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L4852). https://github.com/twbs/bootstrap/pull/19631

`padding: .2em .6em 3em;`

| top | horizontal | bottom |
| --- | --- | --- |
| .2em | .6em | .3em |

The `top` padding is bigger than the `bottom` padding.

So this should fix the issue:

`padding: .3em .6em;`

| vertical | horizontal |
| --- | --- |
| .3em | .6em |

**Comment by FezVrasta** [comment]
I repeat, don't play with paddings, use line-height..

**Comment by HeliumSquid** [comment]
Could you elaborate on that please? Why should the `line-height` be altered and not the `padding`?

**Comment by FezVrasta** [comment]
You are just trying to increase the space took by 1 line of text, this is called `line-height` and has its own CSS property.

So, you could set `line-height: 1.6em` without having to use paddings at all.

Correct me if I'm missing the point here...

**Comment by rosskevin** [comment]
Based on the linked item and @mdo's comments, I agree that adding the padding fix here is ok.  It should be upstream but they've locked down v3 and that makes sense. @HeliumSquid please add a comment to the end of that line and reference the url to the closed upstream issue so that if we review it later we'll know why it is an anomaly.

**Comment by FezVrasta** [comment]
Uh I see, I didn't looked at the urls he linked :/

**Pull request merged**
