### PR TITLE
add nuget packages

### PR DESCRIPTION
**Pull request by Eonasdan**
This PR add's Nuget package support (how we .Net folks get our stuff). I have not published these packages so that you can be in full control if you want.

I've added a command to the grunt file that will automatically build new packages

`grunt nuget` and `grunt -target=css`

The first option will create the LESS version and the second includes the css.

The [NuGet Package Explorer](http://npe.codeplex.com/) is the easiest way to get packages published to nuget.org. You just need an API key.

**Note** while the version has a `-*` suffix, these packages will only show under the "Include Pre-release"

### CODE REVIEW

**Comment by FezVrasta** [comment]
Sorry I can't integrate support for every package manager of the web... I would need a dedicated repository just to handle them :/

**Comment by Eonasdan** [comment]
trust me, I know how you feel `:/`. This this case, you just have to run two grunt tasks and publish them and you're done.

If you still not interested, I might publish it myself, if that's ok

**Comment by FezVrasta** [comment]
The problem is that I have to run two grunt tasks for this, meteor, bower, gems, bla bla bla... And then they are not two commands anymore.

**Comment by Eonasdan** [comment]
what if you made one task to rule them all and in the darkness publish them?

I really do understand. I get people complaining every other day it seems like to make my datetimepicker (which I would like to port to this project at some point) work on such and such package manager.

**Comment by FezVrasta** [comment]
I'd be glad to merge a PR with such approach, but implementing this I don't want to have thousands of folders in the root folder of this project one for each manager.

If everything could be wrapped inside a single folder then I'd like to merge.

**Comment by ghostsquad** [comment]
+1 on getting this into NuGet. There are a lot of developers that use Visual Studio and NuGet is a very mainstream package management system. I think there's lots of value for the community to have this support.

**Comment by Eonasdan** [comment]
With MVC 6 nuget not going to be the primary delivery method for front-end packages like this. I'm planning on giving an End of Life date for my datetime picker's Nuget package.

Microsoft is going to be expecting you to use Bower for this instead anyway. So there's not much point in making nuget packages for front-end scripts and such.

**Comment by ghostsquad** [comment]
Bower definitely seems like a good alternative. Thanks.

**Comment by amastaneh** [comment]
+1 Nuget

**Pull request closed without merging**
