### PR TITLE
Fixed onChange unexpectedly triggered

### PR DESCRIPTION
**Pull request by jdutriaux**
Checking the value for a checkbox input is not wisely, prefer checking the "checked" attribute, we also need to verify if there is a value in the input because default value (for example a text input) is "" and $(this).attr("value") returns undefined.

Rel #205

### CODE REVIEW

**Comment by FezVrasta** [comment]
you should run `grunt` to compile the project before.

Please read https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md

**Comment by jdutriaux** [comment]
Even if the commit concern only 1 file?

**Comment by FezVrasta** [comment]
yup because that file get minified and moved in the right folders.

**Comment by jdutriaux** [comment]
All right, going to do that ;).

**Comment by jdutriaux** [comment]
Seems to be better now? :smile:

**Comment by FezVrasta** [comment]
There was some mess, I've applied your patch manually. thanks.

**Comment by jdutriaux** [comment]
Thanks :).

**Pull request closed without merging**
