### PR TITLE
Fix 394

### PR DESCRIPTION
**Pull request by Invis1ble**
Variable `@text-color` is overriden by `bootstrap`. It is renamed to `@material-text-color`.

### CODE REVIEW

**Comment by FezVrasta** [comment]
This theme is not designed to be compiled together with the Bootstrap files, I don't get how the variables can collide..

**Comment by Invis1ble** [comment]
The "bug" appears when importing Bootstrap with this theme in same file, for example:

``` less
@import '@{path_bower}bootstrap/less/bootstrap.less';

@path_bootstrap_material: '@{path_bower}bootstrap-material-design/less/';

@import '@{path_bootstrap_material}material-fullpalette.less';
@import '@{path_bootstrap_material}roboto.less';
@import '@{path_bootstrap_material}ripples.less';
```

It is not entirely related to this repository.

**Comment by FezVrasta** [comment]
if you import my theme after the bootstrap files my variables should override the BS ones, it works in this way in the main project where I use it.

**Comment by Invis1ble** [comment]
Yes, I imported bootstrap-material after bootstrap:

``` less
@import '@{path_components}bootstrap.less';
@import '@{path_components}bootstrap-material.less';
```

Looks like some scope magic in less loop (in `_mixins_fullpalette.less`), which overrides `@text-color`.

**Comment by FezVrasta** [comment]
I don't really think this can be a good solution... What we want to accomplish is exactly override the default color so it's a nosense to use a different variable

**Comment by Invis1ble** [comment]
Maybe you are right. But `@text-color` defined only in `.generic-variations()` mixin and used only in this context, as I see... Anyway, thanks for the great work! I'll have to work on workaround for my project if PR  will not merged and there will be no fix for this issue.

**Pull request merged**
