### PR TITLE
Add styling for cards (first draft)

### PR DESCRIPTION
**Pull request by npvn**
This is my implementation of [cards](http://www.google.com/design/spec/components/cards.html), inspired by the work of [Kevin Gimbel](http://codepen.io/kevingimbel/pen/GCDep).

In this first version, I only have styling for square cards. Later we can add other types of cards (rectangle cards, cards with solid color as background,...).

A card will expand to fill all of the available width (e.g. column's width). Card's height will be automatically resized to match width.

Here is an example on how to use it:

``` html
<div class="card">

    <div class="card-height-indicator"></div>

    <div class="card-content">

        <div class="card-image">
            <img src="./image.jpg" alt="Loading image...">
            <h3 class="card-image-headline">Lorem Ipsum Dolor</h3>
        </div>

        <div class="card-body">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>

        <footer class="card-footer">
            <button class="btn btn-flat">Share</button>
            <button class="btn btn-flat btn-warning">Learn More</button>
        </footer>

    </div>

</div>
```

Cards will adapt to column's width. The card below will have width equal to `col-lg-6`:

``` html
<div class="row">
    <div class="col-lg-3"></div>

    <div class="col-lg-6">
        <div class="card">
            ...
        </div>
    </div>

    <div class="col-lg-3"></div>
</div>
```

For demo, visit [material.meteor.com](http://material.meteor.com) and scroll down to the 'Cards' section. Note that the flat buttons on that demo page are different from what we're having now. I will submit another PR for buttons later.

Note: I'm having trouble adding the click ripple effect on card's image. The class I added on [line 7](https://github.com/npvn/bootstrap-material-design/compare/FezVrasta:develop...card?expand=1#diff-ddd979003beabc725be6208094237874R7) of `material.js` doesn't seem to work.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Nice work! I'm not sure the border-radius you have used is correct though.

**Comment by npvn** [comment]
The value in Google's doc is `2dp`. Unfortunately this value means different numbers of pixels depending on screen size, [ranging from 1.5px to 4px](http://labs.rampinteractive.co.uk/android_dp_px_calculator).

I picked `3px` since that looked best to me, but it may be just me. Please feel free to adjust the value as you see fit.

**Comment by npvn** [comment]
P.S. Please also take a look at this issue: `I'm having trouble adding the click ripple effect on card's image. The class I added on line 7 of material.js doesn't seem to work`.

**Comment by FezVrasta** [comment]
`` tag is a self-closing element, so ripples.js can't add the ripple-wrapper element inside it (or better, it can, but the browser does weird things).

You should wrap the img with a `<div>` and apply ripples.js to it

**Comment by FezVrasta** [comment]
I've tried setting the border-radius to 2px:

image

As you can see, the left card is the one took from the Google specs, the right one is your card with 2px radius. They look very similar I think.

**Comment by FezVrasta** [comment]
by the way, currently, ripples.js fits better the material design specs then Waves, consider using it instead of Waves.

**Comment by npvn** [comment]
Thanks for your explanation. I adjusted the border radius to 2px.

About the ripple issue, as you can see in my last commit, I tried to apply ripple effect to the wrapper of the `img`: `.card-image`. That didn't fix the issue though. Clicking on the image doesn't have any effect (no `ripple-wrapper` is created). Do you think this is a problem related to event propagation?

**Comment by FezVrasta** [comment]
yup right, I've noticed it works only if the wrapper is a block element...

Adding `pointer-events: none` fixes the problem, not sure if it can be a solution ^_^"

**Comment by npvn** [comment]
That works perfectly! Thank you.

**Comment by TransitoryBliss** [comment]
Maybe we should consider using ems instead of pixels.

**Comment by npvn** [comment]
@shockwork Which rules should we use ems in? What are the main benefits?

**Comment by npvn** [comment]
@FezVrasta Should this PR be ready for merging now?

**Comment by FezVrasta** [comment]
Okay thank you, I've merged it :)

**Pull request merged**
