### PR TITLE
Dropdown

### PR DESCRIPTION
**Pull request by GradyD**

### CODE REVIEW

**Comment by GradyD** [comment]
This should resolve #520, if there any changes that need to be made just let me know.

**Comment by FezVrasta** [comment]
What are these commits about merging pr 2 3 4?

**Comment by GradyD** [comment]
Those should just be getting my fork/branch up to date.

**Comment by GradyD** [comment]
Is there anything you would like for me to do so you can accept this PR?

**Comment by FezVrasta** [comment]
Hi, no sorry. Just been a bit busy.

**Pull request merged**
