### PR TITLE
Meteor integration and README improvements

### PR DESCRIPTION
**Pull request by dandv**
Hi Federico,

As you might know, the [Meteor](http://meteor.com) community loves Bootstrap and your Material Design theme. We had [a wrapper package](https://github.com/html5cat/bootstrap-material-design/) that @html5cat asked me to help with, so I'm submitting a PR that integrates Meteor packaging directly, along with Travis and Grunt tests.

This PR will let you directly publish updated versions of the library as they become available. All you have to do is create an account at https://meteor.com/ (click _SIGN IN_, then _Create account_). After you've done that, please let me know the name of the account, and I'll add you as a maintainer. (`fezvrasta` is taken because it's the namespace of the organization owning the package).

I've already published the current version of the package on [Atmosphere](https://atmospherejs.com/hammer/hammer) (Meteor's package directory). When you release new versions, you can publish them to Atmosphere with `grunt meteor`.

Thanks & best regards,
Dan & the [Meteor integrations team](https://github.com/raix/Meteor-community-discussions/issues/14)

### CODE REVIEW

**Comment by FezVrasta** [comment]
Hey thanks, looks awesome! Real grammar in my **readme**!

Jokes aside, thanks for the PR, looks awesome. Always wanted to try Meteor but I've never found time to... 

Do I need meteor installed on my PC to run the `grunt meteor` task?

**Comment by FezVrasta** [comment]
My account should be **fezvr4sta**

**Comment by dandv** [comment]
Great, added `fezvr4sta` to the `fezvrasta` Meteor Developer org.

Correct, you need Meteor installed. The `grunt meteor` task will install Meteor, but it's more reliable to [install it separately](https://www.meteor.com/install). You mentioned PC, do you happen to use Windows? In that case, there's a [Windows binary here](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows).

**Comment by FezVrasta** [comment]
I'm on windows currently, I'll switch to mac soon I think :)

Okay when I've some time I'll try to play with it. By the way I think that https://github.com/madrobby/keymaster/pull/140 is right, consider to follow this approach.

**Comment by dandv** [comment]
Agree. I'm trying to figure out how to have a meteor build server that [watches git pushes of tags in a list of repos and publishes to Meteor's Atmosphere](https://github.com/MeteorCommunity/discussions/issues/14#issuecomment-67015028).

**Comment by FezVrasta** [comment]
check out cdnjs, they do something similar I think.

**Comment by paralin** [comment]
I would recommend getting some distro of linux and really customizing it to the way you work. That's what I've done, and while I know a lot of developers like using mac I think it's always nicer to be able to do with your OS exactly what you want :) Plus linux makes working with this stuff very easy.

**Comment by dandv** [comment]
Well, I have a Linode already. Just need to figure out the GitHub watching part.

**Comment by paralin** [comment]
@dandv For watching why not just periodically run git ls-remote to see if there are any updates, pull them if there are, and then check to see if there's a release change in there?

**Comment by FezVrasta** [comment]
Or use the GitHub API
https://developer.github.com/v3/repos/commits/

**Comment by splendido** [comment]
Hei guys,
now we have [autopublish.meteor.com](http://autopublish.meteor.com/) automatically _watching_ tag pushes by creating dedicated [web hooks](https://help.github.com/articles/about-webhooks/) on enabled repositories.

You still need to have a `package.js` file inside the repo and a task to update it, but that's it.
No more need to have meteor installed locally to do the publish.

Generally speaking, if you all think having even one more _package manager_ file inside the repo is something not affordable, we might think to extend autopublish.meteor.com to be able to keep a fork of the main repo (including the `package.js` file) up to date with the upstream.

**Comment by FezVrasta** [comment]
Was trying to publish the new version but I get:

``` sh
spacejam: spawning meteor
'test-packages' is not a Meteor command. See 'meteor --help'.
spacejam: meteor exited with code: 1
>> Exited with code: 3.
Warning: Task "exec:meteor-test" failed. Use --force to continue.

Aborted due to warnings.
```

@dandv?

**Pull request merged**
