### PR TITLE
More renaming for compatibility with Meteor

### PR DESCRIPTION
**Pull request by npvn**
See https://github.com/FezVrasta/bootstrap-material-design/issues/103

@FezVrasta These three files need to be renamed as well. Thank you!

### CODE REVIEW

**Comment by FezVrasta** [comment]
How can you know which one are the main files if all have the .import ?

**Comment by npvn** [comment]
I will have a `main.less` file **inside my package** to `@import` all the styles I need (from `bootstrap-material-design` and also from other projects).

Are you concerned about this naming scheme will be confusing to people? I think that should be fine since we don't have an underscore in the names of these three files, so people would properly know that these are the main stylesheets.

**Comment by FezVrasta** [comment]
I see what you mean but it looks a very ugly hack on the meteor side... Can't you exclude the bower directory from the compilation?

**Comment by FezVrasta** [comment]
What about rename less/ and sass/ folders with a dot as prefix? Them should be ignored

**Comment by npvn** [comment]
Your suggestion helped me spark an idea: The Meteor package api allows us to ignore certain files - do not count them as the package source and Meteor won't process them. On the other hand, in `main.less` the `@import` command is still able to find these files, so we can still import them normally. We can then register `main.less` with Meteor. In short: There's no need to change anything in your repo.

I should have thought of this workaround before. Sorry for taking a lot of your time, and many thanks for your help :)

**Comment by FezVrasta** [comment]
you're welcome, I'll revert the commit when I find some free time

**Pull request closed without merging**
