### PR TITLE
Add .npmignore

### PR DESCRIPTION
**Pull request by tenbits**
Do not publish all the dev. content to the npm.

### CODE REVIEW

**Comment by FezVrasta** [comment]
What if someone wants to use the source code in its project? I use it very often.

**Comment by tenbits** [comment]
In that case, if you need also sources, instead of normal npm dependency, you can add specific `bootstrap-material-design` github commit  to the `package.json` of your application. Then with `npm install` all sources will be fetched. [More info on npmjs docs](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by rosskevin** [comment]
I think if this is changed so that the potential source folders that are also good as distributables are still included, we can accept it.  I assume that the following are just as suitable as sources and as distributables:
- less
- sass

If you omit those from this PR, I'm good with accepting it.  

Thoughts? Others that should be kept?

**Comment by FezVrasta** [comment]
yup excluding less and sass from the gitignore would be okay I think

**Comment by tenbits** [comment]
Ok, ready ...

**Pull request merged**
