### PR TITLE
make checkbox animate quickly when not hover.

### PR DESCRIPTION
**Pull request by cncolder**
it's not a perfect method. need improve.
by the way. add 'Thumbs.db' and '.DS_Store' to .gitignore.

### CODE REVIEW

**Comment by FezVrasta** [comment]
thanks :)

**Comment by cncolder** [comment]
im interest which tool chain do you used now. for test or compress less files.
could we import gulp and browser sync?

**Comment by FezVrasta** [comment]
I was using brackets-less-autocompiler, but now I've added grunt tasks.

**Comment by cncolder** [comment]
yeah. both grunt and gulp. need a way to bundle less files and test.
currently it's hard for test.

use BorwserSync we can change less code. browser will refresh auto.

**Comment by FezVrasta** [comment]
I use brackets wich has a built-in live preview and a plugin which automatically runs my grunt task on every edit... feel free to add support for browsersync if you think it can be useful (i'd rather try brackets)

**Pull request merged**
