### PR TITLE
Fix LICENSE.md

### PR DESCRIPTION
**Pull request by ricordisamoa**
https://www.gnu.org/philosophy/free-sw.html

### CODE REVIEW

**Comment by ricordisamoa** [comment]
I understand that you don't like the term "non-free". Since the term "free software" term is confusing as it stands, you may want to clarify that you mean "free as in beer for non-commercial projects".

**Comment by FezVrasta** [comment]
Or just let users read the entire license file and the contributing file.

I want this project to be as much free as possible, but I don't want allow some stupid child to copy my work and sell it bundled in some wordpress theme. When a license like this will be invented I'll move to it...

**Comment by leoetlino** [comment]
@FezVrasta So if I understand, the main issue is with selling your work or including it in some paid bundles? Is that what “non-profit” in your license means?

**Comment by ricordisamoa** [comment]
@FezVrasta For the record, the license is your unquestionable choice. I only object the term you use when referring to it.
However, calling whoever wants to fork a project "stupid child" is insulting in my opinion.

**Pull request closed without merging**
