### PR TITLE
Fix ripples.js to allow multiple elements using ripples

### PR DESCRIPTION
**Pull request by grvcoelho**
There was a problem with the last update when two or more elements of the page used the ripple effect. This is fixed with this commit.

### CODE REVIEW

**Comment by FezVrasta** [comment]
ty!

**Comment by FezVrasta** [comment]
@grvcoelho  I'm watching the new script and I can't find a way to bind ripples.js to dynamically added elements.
Before it was possible using the target parameter.

Is this feature lost or what?

**Comment by grvcoelho** [comment]
@FezVrasta, how did that work?

**Comment by FezVrasta** [comment]
it added the events using .on() and the selector.

Even, every function related to the specific element is now broken.

For example, it uses the ripple color of the first element of the page instead of using the color of the clicked element. 
Same for the size of the ripple.

You said you had just changed the style of the plugin but looks like most of its features are now broken.

(looks like `self` doesn't refer to the correct element)

**Comment by grvcoelho** [comment]
@FezVrasta, I think it's best to revert this PR I've made, so we don't break things. I'll fix this issues this week and test everything out before pulling again!

**Comment by FezVrasta** [comment]
the master branch is for development so I don't think is a big issue if something doesn't work.

**Comment by grvcoelho** [comment]
Well, that's good, haha! I thought I had screwed things up! Yes the problem is with the `self`! I've just fixed the problem with the colors! I'm gonna send a PR!

**Comment by FezVrasta** [comment]
@grvcoelho any update on the fix?

**Comment by FezVrasta** [comment]
I've fixed most of the problems. I still need to figure out how to re-enable the feature to automatically init dynamically added elements. #344

**Pull request merged**
