### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jensz12**
Mobile compatebility update

### CODE REVIEW

**Comment by GradyD** [comment]
This is not very specific. Coming from a former android developer... There are many different a versions of android and for each version you have different flavors. Not only that but you have many different browsers on android and each one acts slightly different.

To further complicate things, odds are that this does in fact work on android and specific functionality does not work on your specific version/browser. 

Could you open a support ticket saying what feature is not working, what device you are using, what version of android, and what browser?

Thanks!!

**Comment by jensz12** [comment]
I wil do that :-)

Med venlig hilsen
Jens Møller
jens@jensz12.com
+4520547827
Den 19/02/2015 00.47 skrev "Grady Duncan" notifications@github.com:

**Comment by GradyD** [comment]
Perfect, Thanks!!

**Comment by FezVrasta** [comment]
Actually most of the features work on Google Chrome on Android 5 so I can only agree with GradyD

**Pull request closed without merging**
