### PR TITLE
Fixes #18 by directly calling rippleOut instead of using dispatchEvent

### PR DESCRIPTION
**Pull request by waylaidwanderer**
Works when tested.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thank you for the PR, tought this breaks the behavior of ripples.js.

More specific: if you click and hold the mouse on a button, the ripple should not disappear until you end the "mousedown" event on the element. With your fix instead when you mousedown the element the ripple automatically disappears after the N ms set by default.

By the way is not the dispatchEvent the problem, the problem seems to be this part of code:

```
if (!mouseDown) {  // <<<< THIS
     rippleOut($ripple);
}
```

Probably clicking fastly floods the mouseDown detector and make the "if" statement always false...

**Comment by waylaidwanderer** [comment]
Ah, I was unaware that's how it was supposed to work. There's probably another solution then.

**Comment by FezVrasta** [comment]
Sorry again... the ripples can be more than one in the specifics of Paper elements... Please check out this link to test the beahvior:

http://www.polymer-project.org/components/paper-elements/demo.html#paper-button

**Comment by waylaidwanderer** [comment]
Ah I see. Thanks for the link! I'll just make a new pull request when I finally fix it, haha.

**Pull request closed without merging**
