### PR TITLE
Ripple color for flat buttons

### PR DESCRIPTION
**Pull request by npvn**
The old code doesn't seem to work properly.

### CODE REVIEW

**Comment by FezVrasta** [comment]
why do you apply it only to flat buttons?

**Comment by npvn** [comment]
As I've noted in the code, for non-flat elements we should work on an algorithm to determine the most appropriate ripple color. Because if we pick a fixed color there will be cases when the ripple color seems too bold or too weak compared to the target element's background.

**Comment by FezVrasta** [comment]
I've just released a new version of ripples.js, fixes some problems with the ripples color and adds support for mobile devices.

I think the ripple color is good, I can't really see where is the problem.

**Comment by npvn** [comment]
Now that I think about it, if the ripple isn't noticeable then we can easily adjust `color` of the target element into something more stand out.

Looks like your recent commits have covered this pull request. I'll close it now.

**Pull request closed without merging**
