### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by FezVrasta** [comment]
Why this? The master branch is for development, if you want a stable one you should install the ones from git tags

**Comment by kkirsche** [comment]
I don't understand what you said at all. Bower uses git tags. Version isn't used.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by FezVrasta** [comment]
>  Most of the info in bower.json is currently mainly used for the package's own record keeping, and isn't kept by the bower registry.

**Pull request closed without merging**
