### PR TITLE
Make markup changes idempotent

### PR DESCRIPTION
**Pull request by mintuhouse**
(on a ruby on rails application with turbolinks)
When I press browser back and forward, the initialization code runs again creating double elements

### CODE REVIEW

**Comment by FezVrasta** [comment]
This should be handled by the notmdproc filter already. Probably there is something wrong there...

**Comment by mintuhouse** [comment]
notmdproc is working if I reinitialize the element in same page. 
But in my setup (with rails/turbolinks), when I press back button and forward button to come back to same page, 
- initialization code is reexecuted (as expected), 
- the mark from previous run is already present(as expected)
- but the $(element).data("mdproc") doesn't return anything (may be normal behaviour - not sure) 
- Any JS behaviour initialization on them is also lost.

That is why I chose to create the new elements only if they are not already present but the JS initialization code would execute always (based on notmdproc).

**Comment by rosskevin** [comment]
If `notmdproc` is not working, we should fix it, not spread a bunch of changes throughout the code to check for existence of these elements.  v4 is slightly different but worth looking at https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/js/src/bootstrapMaterialDesign.js#L176

I haven't tested it with turbolinks yet, but I expect it to work because we are using it directly from the bootstrap implementation.

**Comment by mintuhouse** [comment]
From the latest turbolinks [docs](https://github.com/turbolinks/turbolinks/blob/93f56a107549ed00c5609fbc09190b6d77008d60/README.md#understanding-caching), it seems to discard any associated data from the cached pages. So notmdproc/data based solution may not work.

I have a created a sample app to reproduce the scenario. [source](https://github.com/mintuhouse/material_turbolinks) and [heroku](https://mighty-shelf-51883.herokuapp.com/)

Steps to reproduce
- Navigate to Bootstrap Test link
- Use browser back
- Come to Bootstrap Test link using browser forward

**Comment by rosskevin** [comment]
Thank you for the effort to create the sample.  I assume behavior is the same, but would you mind bumping rails to the latest release? The have turbolinks 5.0.0.beta2 js, not sure if that means the gem is 5.0.0.beta or beta2

From their features section on the readme:

> Respects the web. The Back and Reload buttons work just as you’d expect. Search engine-friendly by design

It looks like it may be as simple as changing when the init is called (that would be nice):  https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads

Can you experiment with the link above (without material.js changes)?  

I'm wondering:
1. if turbolinks users just need to use init with a different hook, or
2. turbolinks 5.0.0.beta has a bug since it declares it _respects the web_

**Comment by mintuhouse** [comment]
I have update the sample to latest version of rails and can confirm that issue exists. 
1. Right now the reinitialization is happening via arrive.js. Even if I try to change the event hook, I feel the same problem would eventually come as `data('mdproc')` guard will fail. 
2. Raised an [issue](https://github.com/turbolinks/turbolinks/issues/30) on turbolinks repo since the behaviour is different from normal web.
   Can you point me to the bootstrap implementation of mdproc or the keyword I need to look for? It may get more audience if I am able to reproduce it on one of bootstrap's core elements.

**Comment by rosskevin** [comment]
[This is how BS does it](https://github.com/twbs/bootstrap/blob/master/js/alert.js#L67).

[This is how our v4 and BSv4 does it](https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/js/src/radio.js#L69).  These are effectively the same thing.

Our v3 is different in that it declares and uses a filter, but it does seem like a reasonable approach.  I'm open to changing it to using the BS approach, I've already done it for v4-dev.

**Comment by rosskevin** [comment]
Any updates to this PR?

**Comment by rosskevin** [comment]
I think this is an important issue,  but I'm closing as in active.

**Pull request closed without merging**
