### PR TITLE
fixed the change of wrong extension

### PR DESCRIPTION
**Pull request by studio3104**
Hi.
Perhaps, you have incorrectly specified extension?
Thank you confirmation.

### CODE REVIEW

**Comment by FezVrasta** [comment]
I'm not the maintainer of the sass version btw I think it's just a mistake

**Comment by studio3104** [comment]
I wish bump up version of bower too. kind regards :) @FezVrasta

**Comment by FezVrasta** [comment]
done with 0.1.4

**Comment by studio3104** [comment]
thanks a lot !!

**Pull request merged**
