### PR TITLE
Browserify support.

### PR DESCRIPTION
**Pull request by jesusprubio**

### CODE REVIEW

**Comment by FezVrasta** [comment]
Hello, why do you bundle all the js in the same file? Wouldn't be better keep them separated?

**Comment by jesusprubio** [comment]
Yep, you're right. Only to be sure, do you mean to separate "material" and "ripples"? And this way to be able to load only the material and vice versa? :)

**Comment by FezVrasta** [comment]
yes exactly

**Comment by jesusprubio** [comment]
After some testing and research now any library can be loaded individually. Due to Browserify nature the only way to achieve this (without including the whole code in the module) is having two different NPM packages. The second one is located under "dist/js/npm/bootstrap-material-ripples", it should be published to the NPM registry like the main one.

I'm reading in the doc: "At the moment RipplesJS does not have its own repository but it will probably have one in the future.". When you do this it will be more confortable to manage this stuff.

Thanks :)

**Comment by RomainLanz** [comment]
Maybe squash?

**Comment by jesusprubio** [comment]
Bad approach, corrected here: https://github.com/FezVrasta/bootstrap-material-design/pull/467

**Pull request closed without merging**
