### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by TransitoryBliss**
You might want to change your github password..

### CODE REVIEW

**Comment by FezVrasta** [comment]
fuck -.-" stupid git extensions... thanks...

**Comment by TransitoryBliss** [comment]
No problem =)

**Comment by FezVrasta** [comment]
I've overwritten the commit but I can't find a way to remove the information from this PR, do you know how can I do?

**Comment by TransitoryBliss** [comment]
You can purge it - but that will cause all kinds of problems for people who have cloned it as you rewrite history.

``` bash
git filter-branch --index-filter \
'git update-index --remove package.json' <introduction-revision-sha1>..HEAD
git push --force --verbose --dry-run
git push --force
```

And then create the package.json again. I would suggest just changing your password on all the places you use it.

I can do it for you if you give me collaborator access temporarily.

**Comment by FezVrasta** [comment]
opus I've already rewritten some commits :\ damn

**Comment by TransitoryBliss** [comment]
You should be fine mate! :dancers:

**Pull request merged**
