### PR TITLE
Prevent checkbox/radio animatation on page load

### PR DESCRIPTION
**Pull request by shannabarnard**
Fix for issue #525 opened on Mar 24, 2015

### CODE REVIEW

**Comment by rosskevin** [comment]
Thank you, this is a step in the right direction as it removes the ripple animate on load, but the checkbox does still animate.  Of note is that the radio still has the animate ripple too.

The best way to see this locally is to `grunt serve` and refresh 
[http://localhost:8040/bootstrap-elements.html#forms](http://localhost:8040/bootstrap-elements.html#forms)

You can also see it on the [docs site](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#forms) (without your changes)
1. Do you want to take a shot at the check mark animation too or just leave this as removing the ripple on load or just leave this pull as-is?
2. Any chance you want to apply this same thing to the radio?

**Comment by shannabarnard** [comment]
Will apply this same thing to the radio and investigate the check mark animation. Update to follow soon.

**Comment by mintuhouse** [comment]
:+1:  This is a nice thing to have, I merged this patch our codebase. Is there any work which is yet to be done on this branch?

**Comment by rosskevin** [comment]
@shannabarnard, I didn't see a comment from you.  I'm not notified of the commits on your branch.  Is this good to go?

P.S. please try to avoid committing `dist` files, they make a mess of reviewing any PRs.  I'm working on a change on v4 so this isn't a problem, but just a future note that it makes it much harder to see the work.

**Comment by shannabarnard** [comment]
Hi

Yep good to go. Will remember regarding the dist folder in the future.

Thanks
Shanna

**Comment by rosskevin** [comment]
I will get this soon, I have some other projects that I'm tied up with at the moment.

**Comment by rosskevin** [comment]
Will be releasing 0.5.9 today.

**Pull request merged**
