### PR TITLE
Update to a cleaner GitHub 'ribbon'.

### PR DESCRIPTION
**Pull request by cquanu**
### For bootstrap-elements.html

Old
old

New
clean

### CODE REVIEW

**Comment by cquanu** [comment]
### For index.html

Old
old

New
new

**Comment by FezVrasta** [comment]
Build is failing

**Comment by cquanu** [comment]
My bad, will fix.

**Comment by cquanu** [comment]
Alright problem fixed @FezVrasta.

**Comment by FezVrasta** [comment]
Thanks!

**Pull request merged**
